### ISSUE TITLE
error: undefined reference to 'tflite::FlatBufferModel::~FlatBufferModel()'

### ISSUE THREAD

**Issue by PuckLiu** [liusanchuan/awesome-android-jni#1]
你好，请问用编译好的libtensorflowLite.so库再开发jni的时候，build报这个错是为啥呢？头文件用的include目录里的文件。现象是只要在cpp文件里声明std::unique_ptr<tflite::FlatBufferModel> model;就报这个错 Android/sdk/ndk/17.2.4988734/sources/cxx-stl/llvm-libc++/include/memory:2233: error: undefined reference to 'tflite::FlatBufferModel::~FlatBufferModel()'
报错截图：![build error1](https://user-images.githubusercontent.com/22793369/102434534-e7c56700-404f-11eb-868b-a13c64bd325a.png)
Cmake文件：[CMakeLists.txt](https://github.com/liusanchuan/awesome-android-jni/files/5706566/CMakeLists.txt)
.so文件路径
![fold](https://user-images.githubusercontent.com/22793369/102434807-79cd6f80-4050-11eb-87e3-61375a73b82c.png)
已经找了一个多星期的bug了，还是没头绪，求赐教

**Comment by liusanchuan** [comment]
可以确定是头文件配置的问题。我之前也碰到过这个错误，主要是由于Cmake中的头文件的路径问题，我之所以写成了下面这种样子（同样的路径导入了两次，很无解），也是试了各种方法的结果：

```shell
# 下面这三个路径是导入头文件，是从 cmakelists文件到include头文件的位置
include_directories(${CMAKE_SOURCE_DIR}/include/flatbuffers)
include_directories(${CMAKE_SOURCE_DIR}/include/tensorflow)
include_directories(${CMAKE_SOURCE_DIR}/include)
```
你可以调整成
```shell
include_directories(${CMAKE_SOURCE_DIR}/include)
```
或者
```shell
include_directories(${CMAKE_SOURCE_DIR}/include/flatbuffers)
```
再试一下导入的情况，

**Comment by PuckLiu** [comment]
好，我之前也试过修改头文件导入，但是仍然不行，我再试试看。感谢~

**Comment by PuckLiu** [comment]
更新：
目前还是报错，而且报错范围缩小到：error: undefined reference to 'tflite::DefaultErrorReporter()'

所有用到 'tflite::DefaultErrorReporter()'的地方都会报这个错，单独使用其他类或者调用方法都是好的，只有初始化对象的类里调用过'tflite::DefaultErrorReporter()'就会报错。
按理说头文件的引用应该是正确的，因为同一个目录里的部分文件可以正常调用的。

**Comment by liusanchuan** [comment]
这个我还没见过。你的头文件是怎么导入的，尖括号还是双引号，



---Original---

**Comment by PuckLiu** [comment]
双引号

#include "include/tensorflow/lite/interpreter.h"
#include "include/tensorflow/lite/kernels/register.h"
#include "include/tensorflow/lite/model_builder.h"

**Comment by liusanchuan** [comment]
我这边也没法复现出你的错误，但是一般提示未定义变量，都是路径配置的问题。



---Original---

**Comment by PuckLiu** [comment]
我现在在尝试单独把这个ErrorReporter的和相关的类剥离出来编译，看有没有问题。可能也是哪里的配置问题吧，这种环境上的差异还是多坑的。

**Comment by liusanchuan** [comment]
其实我们现在更常用Java的aar包



---Original---

**Comment by PuckLiu** [comment]
> 其实我们现在更常用Java的aar包
> […](#)
> ---Original--- From: "LiuYH"<notifications@github.com&gt; Date: Thu, Dec 17, 2020 12:29 PM To: "liusanchuan/awesome-android-jni"<awesome-android-jni@noreply.github.com&gt;; Cc: "Comment"<comment@noreply.github.com&gt;;"三川"<2194167956@qq.com&gt;; Subject: Re: [liusanchuan/awesome-android-jni] error: undefined reference to 'tflite::FlatBufferModel::~FlatBufferModel()' (#1) 我现在在尝试单独把这个ErrorReporter的和相关的类剥离出来编译，看有没有问题。可能也是哪里的配置问题吧，这种环境上的差异还是多坑的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

aar包方便，不过我现在要改c++代码，所以必须再手动编译。
